---
- include_tasks: staging_wsgi_files.yml
  when: "'staging' in group_names"
  tags:
    - apache

- include_tasks: modern_gettext.yml
  tags:
    - modern_gettext

- import_tasks: extract_apptor_test_config.yml
  tags:
    - functional_test
